version: '3'
services:
  router:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      kv:
    environment:
      - TARANTOOL_HTTP_PORT=8082
      - TARANTOOL_ADVERTISE_URI=router:3301
      - TARANTOOL_WORK_DIR=/data/tarantool
      - TARANTOOL_INSTANCE_NAME=router

  storage:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      kv:
    environment:
      - TARANTOOL_ADVERTISE_URI=storage:3301
      - TARANTOOL_WORK_DIR=/data/tarantool
      - TARANTOOL_INSTANCE_NAME=storage

networks:
  kv:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
